---
- name: Installing monitoring services in ubuntu
  hosts: ubuntu
  roles:
    - elk-ubuntu
    - nagios-ubuntu
    - grafana-ubuntu
    - Prometheus_UBUNTU

- name: Installing monitoring services in centos
  hosts: centos
  roles:
    - elk-centos
    - nagios-centos
    - grafana-centos
    - Prometheus_CENTOS

